package:
  name: "sparks"
  version: "0.1.0"
  about:
  summary: "Official implementation of SPARKS, an algorithm for low-dimensional representation of spiking signals."
  source:
  path: ..
  build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python